osx_image: xcode7
language: objective-c

cache:
  - bundler

podfile:
  - Example/Podfile

before_script:
  - make ci

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor.bundle}
  - bundle exec pod install --project-directory=Example

script:
  - make test
  - make lint
